config/routes.rb
Rails.application.routes.draw do

  resources :immagines

  resources :pages, path: 'pagina'
  root 'pages#show', id: 'progetto'

  devise_for :users

end

app/models/immagine.rb
class Immagine < ActiveRecord::Base
   has_attached_file :url, :styles => {
    sky: "1140x470#"
  }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :url, :content_type => /\Aimage\/.*\Z/
  belongs_to :page, touch: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :immagines
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  force_ssl only: :success
end

app/controllers/immagines_controller.rb
class ImmaginesController < ApplicationController
  before_action :set_immagine, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  respond_to :html

  def index
    @immagines = Immagine.all
    respond_with(@immagines)
  end

  def show
    respond_with(@immagine)
  end

  def new
    @immagine = Immagine.new
    respond_with(@immagine)
  end

  def edit
  end

  def create
    @immagine = Immagine.new(immagine_params)
    @immagine.save
    respond_with(@immagine)
  end

  def update
    @immagine.update(immagine_params)
    respond_with(@immagine)
  end

  def destroy
    @immagine.destroy
    respond_with(@immagine)
  end

  private
    def set_immagine
      @immagine = Immagine.find(params[:id])
    end

    def immagine_params
      params.require(:immagine).permit(:url, :page_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]
  respond_to :html

  def index
    @pages = Page.all
    respond_with(@pages)
  end

  def show
    respond_with(@page)
  end

  def new
    @page = Page.new
    respond_with(@page)
  end

  def edit
  end

  def create
    @page = Page.new(page_params)
    @page.save
    respond_with(@page)
  end

  def update
    @page.update(page_params)
    respond_with(@page)
  end

  def destroy
    @page.destroy
    respond_with(@page)
  end

  private
    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit!#(:title, :content, :slug, :published, :immagines)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/immagines_helper.rb
module ImmaginesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/immagines/_form.html.haml
= simple_form_for(@immagine) do |f|
  = f.error_notification

  .form-inputs
    = f.input :url, as: :file
    = f.input :page_id, collection: Page.all

  .form-actions
    = f.button :submit, class: 'btn btn-primary'

app/views/immagines/edit.html.haml
= render 'form'

= link_to 'Show', @immagine
\|
= link_to 'Back', immagines_path

app/views/immagines/index.html.haml
%h1 Listing immagines

%table
  %thead
    %tr
      %th Url
      %th
      %th
      %th

  %tbody
    - @immagines.each do |immagine|
      %tr
        %td= immagine.url
        %td= link_to 'Show', immagine
        %td= link_to 'Edit', edit_immagine_path(immagine)
        %td= link_to 'Destroy', immagine, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Immagine', new_immagine_path

app/views/immagines/new.html.haml
%h1 New immagine

= render 'form'

= link_to 'Back', immagines_path

app/views/immagines/show.html.haml
%p
  = image_tag @immagine.url, class: 'img-responsive'
  - if @immagine.page.present?
    = link_to @immagine.page.title, @immagine.page

= link_to 'Edit', edit_immagine_path(@immagine)
\|
= link_to 'Back', immagines_path

app/views/layouts/application.haml
!!!
%html
  %head
    %title
      = "#{yield :title} - C'è posto per te"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %body
    .container
      .row
        .col-sm-12(style="margin-top: 10px")
          .pull-left
            %h1(style="font-family: 'Georgia'")
              = link_to "C'è posto per te", root_path
          .pull-right.hidden-xs
            %a(href="http://nuoviorizzonti.org" target="_blank")
              = image_tag 'http://www.nuoviorizzonti.org/images/logo.png', style: 'max-width: 100%'
      - if action_name == "show"
        %hr
        .row
          .col-sm-12
            = yield :gallery

      %hr
      .row
        .col-sm-3
          %ul
            %li
              = link_to 'Progetto', page_path('progetto')
              %ul(style="padding-left:18px")
                %li= link_to 'Obiettivi', page_path('obiettivi')
                %li= link_to 'Problemi affrontati', page_path('problemi-affrontati')
                %li= link_to 'Beneficiari', page_path('beneficiari')
                %li= link_to 'Partner', page_path('collaborazioni-partner')
                %li= link_to 'Monitoraggio e valutazione', page_path('monitoraggio-valutazione')
            %li= link_to 'Chi siamo?', page_path('chi-siamo')
            %li= link_to 'Dove siamo?', page_path('dove-siamo')

            %li= link_to 'Cittadella Cielo', page_path('cittadella-cielo')
        - if action_name == "show"
          .col-sm-6
            = yield
          .col-sm-3
            = image_tag 'sedie.jpg', style: 'max-width: 100%; min-width: 100%'
        - else
          .col-sm-9
            = yield

app/views/pages/_form.html.haml
= simple_form_for @page, html: {multipart: true} do |f|
  = f.input :title
  = f.input :content, input_html: {rows: 20}
  = f.input :slug
  = f.input :published
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

- if @page.present?
  %hr
  = simple_form_for Immagine.new, html: {multipart: true} do |f|
    = f.input :url, as: :file, label: 'Immagine'
    = f.input :page_id, as: :hidden, input_html: {value: @page.id}
    = f.submit 'Save', class: 'btn btn-primary'

app/views/pages/_gallery.haml
#carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
  / Wrapper for slides
  .carousel-inner{:role => "listbox"}
    - @page.immagines.each_with_index do |img, index|
      - if index == 0
        .item.active= image_tag img.url(:sky)
      - else
        .item= image_tag img.url(:sky)
  / Controls
  %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Next

app/views/pages/edit.html.haml
= render 'form'

- if user_signed_in?
  %hr

  = link_to 'Show', @page
  \|
  = link_to 'Back', pages_path

app/views/pages/index.html.haml
.table-responsive
  %table.table
    %thead
      %tr
        %th Title
        %th Slug
        %th Published
        %th
        %th
        %th
  
    %tbody
      - @pages.each do |page|
        %tr
          %td= page.title
          %td= page.slug
          %td= page.published
          %td= link_to 'Show', page
          %td= link_to 'Edit', edit_page_path(page)
          %td= link_to 'Destroy', page, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Page', new_page_path

app/views/pages/new.html.haml
%h1 New page

= render 'form'

= link_to 'Back', pages_path

app/views/pages/show.html.haml
- cache ['testo', @page, user_signed_in?] do
  %h2(style="margin-top: 0; text-transform: uppercase; text-rendering: optimizeLegibility; border-bottom: 1px solid #ccc; margin-bottom: 10px; padding-bottom: 10px")= @page.title
  %div(style="font-size: 16px; text-rendering: optimizeLegibility")
    = raw @page.content
  - if user_signed_in?
    %p
      = link_to 'Edit', edit_page_path(@page)
      \|
      = link_to 'Back', pages_path

- content_for :gallery do
  - cache ['gallery', @page, @page.immagines.size] do
    - if @page.immagines.size > 1
      = render 'gallery'
    - else
      = image_tag @page.immagines.first.url(:sky), class: 'img-responsive' if @page.immagines.present?


- content_for :title do
  = @page.title